# Generated by Django 4.2.30 on 2026-07-13 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(blank=True, max_length=255)),
                ('hospital', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('meeting', 'Meeting'), ('call', 'Phone Call'), ('email', 'Email'), ('virtual', 'Virtual'), ('other', 'Other')], max_length=50)),
                ('summary', models.TextField()),
                ('key_points', models.TextField(blank=True, default='[]')),
                ('sentiment', models.CharField(blank=True, max_length=50)),
                ('next_steps', models.TextField(blank=True)),
                ('created_by', models.CharField(default='field_rep', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='hcp.hcp')),
            ],
            options={
                'ordering': ['-interaction_date'],
            },
        ),
    ]
